### ISSUE TITLE
File to import not found

### ISSUE THREAD

**Issue by salihsagdilek** [blocknotes/activeadmin_medium_editor#1]
hello i given an error;

File to import not found or unreadable: ./medium_editor/medium_editor.
Load paths

**Comment by blocknotes** [comment]
Hi @salihsagdilek 
Did you followed the install steps in the README?
Where do you get this error (on the server / on the console)?
Can you post the entire stack trace of the error?

**Comment by salihsagdilek** [comment]
yea i followed readme install steps;
```
Sass::SyntaxError at /admin_users/1
File to import not found or unreadable: ./medium_editor/medium_editor.
Load paths:
  /var/www/sh/app/assets/javascripts
  /var/www/sh/app/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin_medium_editor-0.1.2/app/assets/javascripts
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin_medium_editor-0.1.2/app/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_skin-0.0.12/app/assets/images
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_skin-0.0.12/app/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/app/assets/images
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/app/assets/javascripts
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/app/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/vendor/assets/javascripts
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activeadmin-1.1.0/vendor/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/formtastic-3.1.5/app/assets/stylesheets
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.3/lib/assets/compiled
  /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.3/lib/assets/compiled
```

**Comment by blocknotes** [comment]
This path is strange "./medium_editor/medium_editor"...
The import line should be: `@import 'activeadmin/medium_editor_input';`
Can you show me your "app/assets/stylesheets/active_admin.scss" (or sass)?
You could also try to clean & compile the assets:
`rake assets:clean`
`rake assets:precompile`

**Comment by salihsagdilek** [comment]
again same problem
its my app/assets/stylesheets/active_admin.scss
```scss
// SASS variable overrides must be declared before loading up Active Admin's styles.
//
// To view the variables that Active Admin provides, take a look at
// `app/assets/stylesheets/active_admin/mixins/_variables.scss` in the
// Active Admin source.
//
// For example, to change the sidebar width:
// $sidebar-width: 242px;
// Active Admin's got SASS!
@import "active_admin/mixins";
@import "active_admin/base";
@import "active_skin";

@import 'activeadmin/medium_editor_input';
@import 'activeadmin/medium_editor/themes/default'; // or another theme

// Overriding any non-variable SASS must be done after the fact.
// For example, to change the default status-tag color:
//
//   .status_tag { background: #6090DB; }
#footer {
  background-color: $skinHeaderBck;
}

#switchLanguage {
  position: relative;
  span {
    color: $skinActiveColor;
    font-size: 16px;
    cursor: pointer;
  }
  p {
    display: inline-block;
    float: right;
  }
  > ul {
    position: absolute;
    bottom: 100%;
    margin: 0;
    left: 0;
    display: none;
    background-color: #fff;
    list-style: none;
    padding: 0;
    li {
      a {
        font-size: 16px;
        padding: 5px 10px;
        text-decoration: none;
        display: block;
        &:hover {
          background-color: $skinHeaderBck;
          color: #fff;
        }
      }
    }
  }
  &:hover {
    > ul {
      display: block;
    }
  }
}

```
